### ISSUE TITLE
Creating a WebSocket Bind Model to a non-existent component crashes the Nexus

### ISSUE THREAD

**Issue by hex-for-hecate** [GPII/nexus#21]
## Describe the bug
Opening a WebSocket connection to the `bindModel` endpoint with a path without a component at it causes a fatal error.

### To reproduce
1. Start a nexus instance.
2. In the terminal, execute `wscat -c ws://localhost:9081/bindModel/example1/a`.
3. See error

### Expected behavior
The nexus server should respond with an error and then close the WebSocket connection.

## Technical details
Complete server logs with stack trace:
```
$ node nexusServer.js
Infusion at path /Users/$/infusion-nexus/node_modules/infusion is at top level
21:36:27.864:  Registering module infusion-nexus from path /Users/$/infusion-nexus/
21:36:27.865:  Registering module infusion from path /Users/$/infusion-nexus/node_modules/infusion/
21:36:27.865:  Registering module infusion from path /Users/$/infusion-nexus/node_modules/infusion
Resolved infusion from path /Users/$/infusion-nexus/node_modules/kettle/node_modules/infusion/src/module to /Users/$/infusion-nexus/node_modules/infusion
21:36:27.871:  Registering module kettle from path /Users/$/infusion-nexus/node_modules/kettle
21:36:28.474:  Registering module infusion-nexus from path /Users/$/infusion-nexus
21:36:28.537:  Registering request handler {
    "route": "/defaults/:gradeName",
    "method": "get",
    "type": "fluid.nexus.readDefaults.handler"
}
21:36:28.538:  Registering request handler {
    "route": "/defaults/:gradeName",
    "method": "put",
    "type": "fluid.nexus.writeDefaults.handler"
}
21:36:28.538:  Registering request handler {
    "route": "/components/:path",
    "method": "post",
    "type": "fluid.nexus.constructComponent.handler"
}
21:36:28.538:  Registering request handler {
    "route": "/components/:path",
    "method": "delete",
    "type": "fluid.nexus.destroyComponent.handler"
}
21:36:28.539:  Registering request handler {
    "route": "/bindModel/:componentPath/:modelPath",
    "type": "fluid.nexus.bindModel.handler"
}
21:36:28.540:  Opening Kettle Server on port 9081
21:36:28.543:  Kettle Server bq4kglkv-49 is listening on port 9081
21:36:41.453:  Invoking handler fluid.nexus.bindModel.handler for route /bindModel/:componentPath/:modelPath with expectedGrade kettle.request.ws
21:36:41.465:  Kettle server allocated request object with type fluid.nexus.bindModel.handler
21:36:41.467:  Received WebSockets connection on path /bindModel/testSheet/sheet1
21:36:41.468:  FATAL ERROR: Uncaught exception: Cannot read property 'applier' of undefined
TypeError: Cannot read property 'applier' of undefined
    at fluid.nexus.bindModel.bindWs (/Users/$/infusion-nexus/src/nexusGrades.js:180:45)
    at togo (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidIoC.js:2703:33)
    at fluid.event.firer.fire (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/Fluid.js:1712:40)
    at /Users/$/infusion-nexus/node_modules/kettle/lib/KettleServer.ws.js:58:37
    at wrappedCallback (/Users/$/infusion-nexus/node_modules/kettle/lib/KettleRequest.js:115:33)
    at WebSocketServer.<anonymous> (/Users/$/infusion-nexus/node_modules/kettle/lib/KettleServer.ws.js:59:11)
    at WebSocketServer.emit (events.js:223:5)
    at /Users/$/infusion-nexus/node_modules/ws/lib/websocket-server.js:98:18
    at WebSocketServer.completeUpgrade (/Users/$/infusion-nexus/node_modules/ws/lib/websocket-server.js:331:5)
    at /Users/$/infusion-nexus/node_modules/ws/lib/websocket-server.js:247:16
    at /Users/$infusion-nexus/node_modules/kettle/lib/KettleRequest.ws.js:78:9
    at Function.fluid.promise.pushHandler (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidPromises.js:88:21)
    at Object.that.then (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidPromises.js:35:27)
    at kettle.request.ws.handleFullRequest (/Users/$/infusion-nexus/node_modules/kettle/lib/KettleRequest.ws.js:76:24)
    at fluid.componentConstructor.invokeInvoker [as handleFullRequest] (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidIoC.js:2635:29)
    at kettle.request.initiateHandleRequest (/Users/$/infusion-nexus/node_modules/kettle/lib/KettleRequest.js:299:13)
    at togo (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidIoC.js:2703:33)
    at fluid.event.firer.fire (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/Fluid.js:1712:40)
    at fluid.concludeComponentInit (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidIoC.js:1475:30)
    at /Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidIoC.js:2090:29
    at Array.forEach (<anonymous>)
    at localWorkflowTask (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidIoC.js:2089:41)
    at Object.invokeNext (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidPromises.js:260:56)
    at Function.fluid.promise.resumeSequence (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidPromises.js:240:39)
    at Function.fluid.promise.progressSequence (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidPromises.js:221:23)
    at Function.fluid.promise.resumeSequence (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidPromises.js:249:31)
    at Function.fluid.promise.progressSequence (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidPromises.js:221:23)
    at Function.fluid.promise.resumeSequence (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidPromises.js:249:31)
    at Function.fluid.promise.progressSequence (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidPromises.js:221:23)
    at Function.fluid.promise.resumeSequence (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidPromises.js:249:31)
    at commitPotentiae (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidIoC.js:2212:31)
    at Object.fluid.tryCatch (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/Fluid.js:245:24)
    at Object.fluid.commitPotentiae (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidIoC.js:2201:15)
    at fluid.concludeAnyTransaction (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/FluidIoC.js:1369:19)
    at fluid.event.firer.fire (/Users/$/infusion-nexus/node_modules/infusion/src/framework/core/js/Fluid.js:1712:40)
    at Function.kettle.server.checkCreateRequest (/Users/$/infusion-nexus/node_modules/kettle/lib/KettleServer.js:201:51)
    at /Users/$/infusion-nexus/node_modules/kettle/lib/KettleServer.js:222:35
    at Object.verifyClient (/Users/$/infusion-nexus/node_modules/kettle/lib/KettleServer.ws.js:49:13)
    at WebSocketServer.handleUpgrade (/Users/$/infusion-nexus/node_modules/ws/lib/websocket-server.js:242:22)
    at Server.upgrade (/Users/$/infusion-nexus/node_modules/ws/lib/websocket-server.js:97:16)
    at Server.emit (events.js:223:5)
    at onParserExecuteCommon (_http_server.js:606:14)
    at onParserExecute (_http_server.js:547:3)
21:36:41.473:  Current activity:
21:36:41.473:      while firing to listener to event named onBindWs of component component { typeName: "fluid.nexus.bindModel.handler id: bq4kglkv-127" gradeNames: ["kettle.request","kettle.request.ws","fluid.nexus.bindModel.handler"]} at path config-bq4kglkv-47.server.nexus.requests.request
21:36:41.473:      while invoking invoker with name handleFullRequest and record {
    "func": undefined,
    "funcName": "kettle.request.ws.handleFullRequest",
    "listener": undefined,
    "this": undefined,
    "method": undefined,
    "changePath": undefined,
    "value": undefined,
    "args": {
        "value": "NO_VALUE"
    },
    "componentSource": "kettle.request.ws"
} holding component component { typeName: "fluid.nexus.bindModel.handler id: bq4kglkv-127" gradeNames: ["kettle.request","kettle.request.ws","fluid.nexus.bindModel.handler"]} at path config-bq4kglkv-47.server.nexus.requests.request
21:36:41.474:      while firing to listener to event named onCreate of component component { typeName: "fluid.nexus.bindModel.handler id: bq4kglkv-127" gradeNames: ["kettle.request","kettle.request.ws","fluid.nexus.bindModel.handler"]} at path config-bq4kglkv-47.server.nexus.requests.request
21:36:41.474:  Error in forwarding result {
    "isError": true,
    "message": "Cannot read property 'applier' of undefined"
} to promise reject: promise has already received resolve
```

### Desktop
 - OS: MacOS Mojave 10.14.5
 - Node.js Version 12.14

**Comment by hex-for-hecate** [comment]
The issue is being tracked at https://issues.fluidproject.org/browse/FLUID-6504
